# Generated by Django 2.1.7 on 2019-03-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
