# Generated by Django 2.1.7 on 2019-03-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20190327_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
